### ISSUE TITLE
(index):1 Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by cakeph** [renatomarinho/laravel-page-speed#100]
## Detailed description

Provide a detailed description of the change or addition you are proposing.

Make it clear if the issue is a bug, an enhancement or just a question.

## Context

Why is this change important to you? How would you use it?

How can it benefit other users?

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. PHP 7.1, HHVM 3):
* Operating system and version (e.g. Ubuntu 16.04, Windows 7):
* Link to your project:
* ...
* ...

**Comment by souhailkaoussi-pro** [comment]
Why is this closed, it isn't solved.

I wasted 3 days debugging an issue and this was the package causing it.
