### ISSUE TITLE
Found a bug when the img path contains spaces.

### ISSUE THREAD

**Issue by TELstatic** [renatomarinho/laravel-page-speed#105]
## Detailed description

When the img path contains spaces, the image does not load.

I think this was a bug.

## Context

none.

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## Your environment

* Version used (PHP 7.1,Laravel5.6)
* Operating system and version (Windows 10)

**Comment by lucasMesquitaBorges** [comment]
Hi @TELstatic I tested this error in some cases but I haven't found the error you reported.

How this issue is a bit old, I'll close it.

If you still have this problem, please feel free to open a new issue.

**Comment by TELstatic** [comment]
> Hi @TELstatic I tested this error in some cases but I haven't found the error you reported.
> 
> How this issue is a bit old, I'll close it.
> 
> If you still have this problem, please feel free to open a new issue.

composer.json
"renatomarinho/laravel-page-speed": "^1.8"

When use middleware `\RenatoMarinho\LaravelPageSpeed\Middleware\RemoveQuotes::class`
and image url like `http://alproducts.oss-cn-shanghai.aliyuncs.com/Images/mbk5ez/test (1).jpg`.

The html resource will be render as `<img src=//alproducts.oss-cn-shanghai.aliyuncs.com/Images/mbk5ez/test (1).jpg alt="">`

Picture cannot be displayed normally. @lucasMesquitaBorges

**Comment by lucasMesquitaBorges** [comment]
@TELstatic Thank you! I'll be working on this bug.
