### ISSUE TITLE
Facebook comment plugins doesn't work after install this package

### ISSUE THREAD

**Issue by HasanurHimel** [renatomarinho/laravel-page-speed#107]
## Doesn't show facebook comment system

 i use facebook comment plugins in frontend before install this package it worked perfectly . after install this package html's are minified and others function are work properly but my facebook comment section doesn' t show . how to overcome it.

**Comment by nattaphong253325332533** [comment]
comment line in Kernel.php
// \RenatoMarinho\LaravelPageSpeed\Middleware\TrimUrls::class,

**Comment by winex01** [comment]
Disqus not working also after installing this package.

**Comment by joaorobertopb** [comment]
Hi guys

I'm working on the fix.

**Comment by lucasMesquitaBorges** [comment]
This issue was resolved at [2.0.0 version](https://github.com/renatomarinho/laravel-page-speed/tree/2.0.0)!
