### ISSUE TITLE
unexpected 'App'

### ISSUE THREAD

**Issue by snaix93** [renatomarinho/laravel-page-speed#113]
Some controllers are crashing because of error "Parse error: syntax error, unexpected 'App' (T_STRING)" 

Most of the pages are working fine but one out of 15 Controllers is dying with this message.

![image](https://user-images.githubusercontent.com/25886550/65133210-ebaca880-da0a-11e9-8a16-60d13c5f457d.png)

The issue is happening only on server, on localhost everything is working fine. 

Controller code:
![image](https://user-images.githubusercontent.com/25886550/65133602-91f8ae00-da0b-11e9-859e-7bdee7742d5a.png)

* Version used ( PHP 7.2, Laravel 5.8 ):
* Operating system and version (Ubuntu):
* Link to your project:
https://www.buchetto.ro/all-products

**Comment by joaorobertopb** [comment]
![image](https://user-images.githubusercontent.com/6556083/65291236-c8781b00-db28-11e9-9d6a-bfb8597fe1e6.png)

It looks like middleware is modifying the controller source code ...
**That's weird!**

There is probably some misconfiguration on the server as the problem does not occur in the local environment.

**Comment by snaix93** [comment]
Is possible to write in the beginning of the controller or model to stop compressing it? Or is any location where I can put rules what to convert and what not? Have tried to do it in laravel-page-speed config but is not working.
