### ISSUE TITLE
remove comment in javascript

### ISSUE THREAD

**Issue by vahidalvandi** [renatomarinho/laravel-page-speed#122]
in javascript inline comment line compress page comment all script
please remove comment in script

/*
*/
and 
//

## Your environment 

 laravel 6

**Comment by lucasMesquitaBorges** [comment]
@vahidalvandi This PR https://github.com/renatomarinho/laravel-page-speed/pull/111 will add this feature.

We're currently working to finish it.

**Comment by lucasMesquitaBorges** [comment]
This issue was resolved at [2.0.0 version](https://github.com/renatomarinho/laravel-page-speed/tree/2.0.0)!
