### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by romather** [renatomarinho/laravel-page-speed#123]
![image](https://user-images.githubusercontent.com/47756883/78458784-69c05c00-768a-11ea-97c3-dee25e1cf85d.png)

**Comment by mvpopuk** [comment]
I just installed this and it's working ... too bad it's abandoned... maybe I'll continue the roadmap on my own... or at least contibute on this one if there's enough interest

**Comment by lucasMesquitaBorges** [comment]
@romather Those abandoned packages aren't a dependency of laravel-page-speed package. Maybe those warnings was from another package you installed, and after that you've required laravel-page-speed. Can you check?

**Comment by lucasMesquitaBorges** [comment]
@romather laravel page speed doesn't require any of those abandoned packages.
It can be another package you've installed.
