### ISSUE TITLE
Repeated white space in string literals removed by CollapseWhitespace

### ISSUE THREAD

**Issue by agwidarsito** [renatomarinho/laravel-page-speed#129]
## Detailed description

If you have a Javascript string that has two spaces within it, such as the following below, then CollapseWhitespaces will remove it.

`let myString = 'hello  world'; //there are double spaces here`

Spaces within strings should be preserved as they're often there for a reason.

## Context

This change is important because strings are literals and should not be altered by post processors.

## Your environment

Version: PHP 7.2
Library version: 1.18.13

**Comment by joaorobertopb** [comment]
Please, use version **2.0**. Thanks!
