### ISSUE TITLE
Add support Laravel 8

### ISSUE THREAD

**Issue by nikonor909** [renatomarinho/laravel-page-speed#131]
Add support for laravel 8

**Comment by kuus** [comment]
Should just be a matter of changing in the `composer.json` to:
```json
    "illuminate/support": "5.3.* || 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^8.0"
```

**Comment by xaniuskarlhall** [comment]
One of the contributors can upgrade accept the pull request or upgrade the package to support version  please.

**Comment by joaorobertopb** [comment]
Hi guys!

PR #132 is already under review.
