### ISSUE TITLE
Purpose of inline page_speed css?

### ISSUE THREAD

**Issue by CaptainCannabis** [renatomarinho/laravel-page-speed#134]
Why is there inline css appended while using the plugin?

![Image 13](https://user-images.githubusercontent.com/5312061/93221429-12143980-f76e-11ea-8be7-dd130afa49a4.png)

**Comment by joaorobertopb** [comment]
This package is inspired by the project: https://www.modpagespeed.com/doc/

Inline CSS is one of several filters available.

> The " Inline CSS "filter reduces the number of requests made by a web page by inserting the contents of small external CSS resources directly into the HTML document. This can reduce the time it takes to display content to the user, especially in older browsers . 
> Refer: https://www.modpagespeed.com/doc/filter-css-inline

if you prefer you can disable this behavior, just **comment the middleware \RenatoMarinho\LaravelPageSpeed\Middleware\InlineCss::class** in the `app/Http/Kernel.php` file.

**Comment by CaptainCannabis** [comment]
Thx!
