### ISSUE TITLE
VueJS class binding broken

### ISSUE THREAD

**Issue by CaptainCannabis** [renatomarinho/laravel-page-speed#135]
I am using vue components with dynamic class bindings. If there is a class-attribute and a vueJS :class-binding the properties get mixed and vue fails rendering.

This ....
![Image 16](https://user-images.githubusercontent.com/5312061/93256163-3a665d00-f79b-11ea-9748-ea97184e2d29.png)

results in ....

![Image 17](https://user-images.githubusercontent.com/5312061/93256196-481be280-f79b-11ea-8fe2-8cc6193bd1d5.png)

it makes no difference if i change "v-bind:class" to the shorthand ":class". Same results.

**Comment by joaorobertopb** [comment]
Hi @CaptainCannabis, thanks for reporting this.

Hey @lucasMesquitaBorges , was this resolved in [version 2.0](https://github.com/renatomarinho/laravel-page-speed/tree/2.x)?

**Comment by CaptainCannabis** [comment]
> Hi @CaptainCannabis, thanks for reporting this.
> 
> Hey @lucasMesquitaBorges , was this resolved in [version 2.0](https://github.com/renatomarinho/laravel-page-speed/tree/2.x)?

i switched to the 2.x branch and commented out the InlineCSS Middleware like yout mentioned [here](https://github.com/renatomarinho/laravel-page-speed/issues/134). It suddenly seem to work :D

![Image 18](https://user-images.githubusercontent.com/5312061/93260884-4570bb80-f7a2-11ea-9deb-e0a01968503b.png)

**Comment by joaorobertopb** [comment]
in version 2.0, we changed the way middlewares is registered.

It is an unstable version still in development, we are testing some things ...

**Comment by CaptainCannabis** [comment]
> in version 2.0, we changed the way middlewares is registered.
> 
> It is an unstable version still in development, we are testing some things ...

I did not test the combination "without InlineCSS Middleware && v1.9". Will see if that would work too.
