### ISSUE TITLE
When the script is written in the blade file, it gives me an error.

### ISSUE THREAD

**Issue by lasamarndi** [renatomarinho/laravel-page-speed#136]
## Detailed description

Provide a detailed description of the change or addition you are proposing.

Make it clear if the issue is a bug, an enhancement or just a question.

## Context

Why is this change important to you? How would you use it?

How can it benefit other users?

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. PHP 7.1, HHVM 3):
* Operating system and version (e.g. Ubuntu 16.04, Windows 7):
* Link to your project:
* ...
* ...

**Comment by lasamarndi** [comment]
error is **Uncaught SyntaxError: Unexpected end of input**

**Comment by elijahcruz12** [comment]
I think the package developer needs more info than this.

**Comment by joaorobertopb** [comment]
Please, use version **2.0**. Thanks!

**Comment by milad777v2** [comment]
i use version 2 but I also getting error
