### ISSUE TITLE
How does the package compared with Google PageSpeed extension for nginx and apache

### ISSUE THREAD

**Issue by tingan** [renatomarinho/laravel-page-speed#144]
Hi,
I have used google Pagespeed extension for nginx (https://developers.google.com/speed/pagespeed/module). I wonder does this package offer any things better than google pagespeed extension? thanks.

**Comment by joaorobertopb** [comment]
Hi @tingan ,

No! This package is just an alternative to the extension, it does not replace it under any circumstances. Whenever possible, preferably for the native page speed module for Nginx or Apache.
