### ISSUE TITLE
Remove comments middleware has error with IE check

### ISSUE THREAD

**Issue by sangnguyenplus** [renatomarinho/laravel-page-speed#18]
Hi @renatomarinho,
My application shows white page when I use RemoveComments middleware.

```
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
```
If I remove IE check, it's works fine.
Please help me check it.
Thank you so much!

**Comment by renatomarinho** [comment]
Hi @sangnguyenplus,

I fixed this issue on version [https://github.com/renatomarinho/laravel-page-speed/tree/1.5.5](1.5.5)

Thanks!
