### ISSUE TITLE
Does this package minify html automatically?

### ISSUE THREAD

**Issue by jafar690** [renatomarinho/laravel-page-speed#21]
i just installed this package in my laravel 5.5 application, and i dont know how to use it since it says in the documentation that for laravel 5.5 user, we just install and thats it. but my html is not getting minified, so am wondering if there is something i should do, any help will be highly appreciated.

**Comment by joaorobertopb** [comment]
Hi,

Next, the \RenatoMarinho\LaravelPageSpeed\Middleware\CollapseWhitespace::class and others - middleware must be registered in the kernel:
```
//app/Http/Kernel.php

protected $middleware = [
    ...
    \RenatoMarinho\LaravelPageSpeed\Middleware\ElideAttributes::class,
    \RenatoMarinho\LaravelPageSpeed\Middleware\InsertDNSPrefetch::class,
    \RenatoMarinho\LaravelPageSpeed\Middleware\RemoveComments::class,
    \RenatoMarinho\LaravelPageSpeed\Middleware\TrimUrls::class,
    \RenatoMarinho\LaravelPageSpeed\Middleware\RemoveQuotes::class,
    \RenatoMarinho\LaravelPageSpeed\Middleware\CollapseWhitespace::class,
]
```

I will review the documentation...
