### ISSUE TITLE
ErrorException PageSpeed.php

### ISSUE THREAD

**Issue by Cannonb4ll** [renatomarinho/laravel-page-speed#29]
Just installed this package in one of my bigger projects to speed up the site.

But right after including, I get this error:

(1/1) ErrorExceptionpreg_replace(): Unknown modifier '/'
--
in PageSpeed.php (line 48)

(And here the whole html is getting spit out)

**Comment by kenzouno1** [comment]
Duplicate #27

**Comment by Cannonb4ll** [comment]
Totally forgot to search... My bad, thanks!

**Comment by kenzouno1** [comment]
You can fix it yourself before waiting for a update #28

**Comment by Cannonb4ll** [comment]
Yes I saw your PR, nice work. Will overwrite the original middleware until there's a update :)
