### ISSUE TITLE
Issue with inline script comment & laravel-debugbar package conflicts

### ISSUE THREAD

**Issue by sangnguyenplus** [renatomarinho/laravel-page-speed#30]
<h2>Detailed description</h2>
<p>In my application, sometimes I have a script in HTML:</p>
<pre><code>&lt;script&gt;
// I need to comment what I want to do here
console.log('something here');
&lt;/script&gt;</code></pre>
<p>Then it throws an error
<em>Uncaught SyntaxError: Unexpected end of input</em></p>
<h2>Context</h2>
<p>I think many people will get this bug when using your package in their apps.</p>
<h2>Possible implementation</h2>
<p>Remove script comment in HTML</p>
<h2>Your environment</h2>
<ul>
<li>PHP version: 7.1</li>
<li>Laravel 5.5</li>
</ul>

**Comment by kenzouno1** [comment]
yep.that conflict with debugbar package

**Comment by acro5piano** [comment]
I use laravel-page-speed with [Laravel Debugbar](https://github.com/barryvdh/laravel-debugbar). 
I faced the error `(index):1 Uncaught ReferenceError: PhpDebugBar is not defined` and solved it by adding debugbar package to skip routes list.

```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Skip Routes
    |--------------------------------------------------------------------------
    */

    'skip' => [
        // ....
        '_debugbar/*',
        // ....
    ],

];
```

For the time being I can remove the error, but removing inline comments from script tag is the best solution.
However, this package is not responsible removing comments from asset files. 
Build tools such as Webpack do that work in general, so this is not a big problem.

**Comment by spaceemotion** [comment]
Additionally, script tags that contain JS that are written in [https://standardjs.com/](Standard JS) produce the following error: `Uncaught SyntaxError: Unexpected identifier`. This only affects the CollapseWhitespace option of course, the rest works as advertised. Cheers!

**Comment by redalpha01** [comment]
As far as I can see, this issue occurs everywhere there's single line comments 
"// Comment"
What we would need is to remove those comments before the whitespaces are removed.

Alternatively, if you have your javascript in a Blade view, you can use the Blade commenting style so that it isn't in the cached view and therefore doesn't cause an issue.

**Comment by spaceemotion** [comment]
Small update as I played around with this a little bit today:

`/\/\*(.*?)\*\//s` seems to works fine for removing multiline comments.

`/\/\/(.*)/` would not work as links that try to preserve the protocol are also getting affected, e.g. `<img src="//example.com/link/to/image.png" />`. Additionally, the order is also very important. This won't work unless the RemoveComments middleware is executed before the CollapseWhitespace one.

**Comment by vesper8** [comment]
the _debugbar should be added to the default list of skipped routes

**Comment by vesper8** [comment]
any update on when the inline // script comments will be added to this package?

currently i find it quite scary because it's so easy to leave those comments in

**Comment by saimpot** [comment]
I was facing the same problems as most of you, and removed inline comments from my script tags, but some stuff kept breaking. I found that in places where I omitted semi-colons that functionality was broken. 

For example
`$(document).on('click', 'input#radio_lawyer', function() { $('#user_perks').hide(); })`

may be valid javascript, in this case is different from 

`$(document).on('click', 'input#radio_lawyer', function() { $('#user_perks').hide(); });`

Adding semicolons fixed this.

**Comment by andreshg112** [comment]
Same here! I'm not using debugbar.

**Comment by CharlieEtienne** [comment]
It's still an issue ! 

Happens with each `// Comment`

**Comment by sera527** [comment]
Same here! I'm not using debugbar.
Happens with each `// Comment`

**Comment by joaorobertopb** [comment]
Hi guys,

I'm working on this fix and running some tests on my Fork...

See:
https://github.com/renatomarinho/laravel-page-speed/compare/master...joaorobertopb:fix-middlewares
