### ISSUE TITLE
can't support with laravel + angular

### ISSUE THREAD

**Issue by sensugaz** [renatomarinho/laravel-page-speed#31]
When laravel-page-speed is enabled Buttons with ng-disabled do not work

laravel 5.4
PHP 7.1.6

**Comment by renatomarinho** [comment]
Hi @sensugaz ,

Can you send me an example?

**Comment by sensugaz** [comment]
before
http://prntscr.com/gyxjth
`<button type="submit" class="btn btn-success btn-block" ng-disabled="form.$invalid || btnLoading">
                                        <span ng-if="!btnLoading">
                                            ล๊อกอิน
                                        </span>
                                        <span ng-if="btnLoading">
                                            <i class="fa fa-circle-o-notch fa-spin"></i>
                                        </span>
                                    </button>`
after
http://prntscr.com/gyxka2

**Comment by cuprous** [comment]
It looks like the issue is on line 11 of ElideAttributes.php: 

` '/disabled=[^ >]*(.*?)/' => 'disabled',`

That's going to remove any expression passed to ng-disabled. Maybe it could be replaced with:

`'/ disabled=[^ >]*(.*?)/' => ' disabled',`

**Comment by renatomarinho** [comment]
thanks, @cuprous !!!

**Comment by cuprous** [comment]
@renatomarinho I didn't think of it when I commented yesterday, but you might want to consider using \s instead of the actual space character so that you catch tabs or newline characters before the disabled attribute.

`'/\sdisabled=[^ >]*(.*?)/' => ' disabled',`

**Comment by sensugaz** [comment]
thank you :)
