### ISSUE TITLE
Inline css background image, always change  to page_speed_xxxx

### ISSUE THREAD

**Issue by rezaple** [renatomarinho/laravel-page-speed#33]
<p>im generate thumbnail image from youtube</p>
<p><code>var content = '&lt;div id="player_' + newId() + '" class="video-player"&gt;&lt;/div&gt;' + '&lt;div class="video-info"&gt;' + '&lt;button class="video-play-button"&gt;&lt;i class="fa fa-play-circle"&gt;&lt;/i&gt;&lt;/button&gt;' + '&lt;div class="caption-content"&gt;&lt;div class="container custom-container-padding"&gt;&lt;div class="row container-header"&gt;' + '&lt;div class="col-md-12"&gt;&lt;p class="truncate-2"&gt;'+ caption +'&lt;/p&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;' + '&lt;div class="video-thumb" style="background-image: url(' + url + ');"&gt;&lt;/div&gt;' + '&lt;/div&gt;'; $this.html(content);</code></p>
<p>but when i enable the laravel page speed, the thumbnail change to this
<code>&lt;div class="video-thumb page_speed_809782230"&gt;&lt;/div&gt;</code></p>
<p>this is my middleware
<code>protected $middleware = [ \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class, \App\Http\Middleware\TrimStrings::class, \App\Http\Middleware\MaintenanceMiddleware::class, \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class, \RenatoMarinho\LaravelPageSpeed\Middleware\InlineCss::class, \RenatoMarinho\LaravelPageSpeed\Middleware\ElideAttributes::class, \RenatoMarinho\LaravelPageSpeed\Middleware\InsertDNSPrefetch::class, \RenatoMarinho\LaravelPageSpeed\Middleware\RemoveComments::class, \RenatoMarinho\LaravelPageSpeed\Middleware\TrimUrls::class, \RenatoMarinho\LaravelPageSpeed\Middleware\RemoveQuotes::class, \RenatoMarinho\LaravelPageSpeed\Middleware\CollapseWhitespace::class, </code></p>
<p>sorry for my bad english</p>

**Comment by renatomarinho** [comment]
Hi @rezaple ,

I will fix it, but to resolve you can remove the middleware InlineCss::class (  \RenatoMarinho\LaravelPageSpeed\Middleware\InlineCss::class ) 

Cheers,

**Comment by romainlp** [comment]
Hi @renatomarinho,

First thanks for the package, had the same issue on an app, should the InlineCss middleware add a !important rule in the generated css ? Might be just a work around.

In my example, i have a header with a css class `.header`, after applying the inlineCss, the CSS class added is correct, but get override by my CSS stylesheet with a rule `.top .header `.

Cheers

**Comment by jafar690** [comment]
@renatomarinho was this issue fixed?

**Comment by joaorobertopb** [comment]
Please, use version **2.0**. Thanks!
