### ISSUE TITLE
Object of class Closure could not be converted to int

### ISSUE THREAD

**Issue by smplyjr** [renatomarinho/laravel-page-speed#34]
I get this error when I add laravel-page-speed classes into Kernel. See [this](https://snag.gy/tlLgbH.jpg). I'm using a fresh install of laravel 5.3

**Comment by joaorobertopb** [comment]
Hi @smplyjr ,

Thank you for notifying.

@renatomarinho, In laravel 5.3 the "every" method of the collection has another behavior...

https://laravel.com/api/5.3/Illuminate/Support/Collection.html#method_every

https://github.com/renatomarinho/laravel-page-speed/blob/48ef09cde108b0dc93ea17f6c18b3cb0fe35f124/src/Middleware/PageSpeed.php#L76
