### ISSUE TITLE
[Suggestion] - Implementing turbolinks

### ISSUE THREAD

**Issue by ConsoleTVs** [renatomarinho/laravel-page-speed#36]
<p>Perhaps implementing turbolinks in some way could also be added in the roadmap?</p>
<p>Just giving ideas :D</p>

**Comment by joaorobertopb** [comment]
Hi @ConsoleTVs,
Thanks for suggestion.

We are currently focusing on bug fixes and the implementation of all filters.

**Comment by ConsoleTVs** [comment]
Yes that's perfect, also this is a front end solution rather than server side, but very usefull to be honest

**Comment by vesper8** [comment]
@ConsoleTVs I'm running it with Turbolinks right now I'm running into other problems which seem unrelated to Turbolinks.. but are you saying that currently the two are incompatible?

**Comment by vesper8** [comment]
I've fixed some of my problems and created issues for the bugs I encountered.

But basically these are my middlewares right now

```
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Frenzy\Turbolinks\Middleware\StackTurbolinks::class,

//        \RenatoMarinho\LaravelPageSpeed\Middleware\InlineCss::class,
        \RenatoMarinho\LaravelPageSpeed\Middleware\ElideAttributes::class,
        \RenatoMarinho\LaravelPageSpeed\Middleware\InsertDNSPrefetch::class,
        \RenatoMarinho\LaravelPageSpeed\Middleware\RemoveComments::class,
//        \RenatoMarinho\LaravelPageSpeed\Middleware\TrimUrls::class,
        \RenatoMarinho\LaravelPageSpeed\Middleware\RemoveQuotes::class,
        \RenatoMarinho\LaravelPageSpeed\Middleware\CollapseWhitespace::class,
    ];
```

So I have InlineCss and TrimUrls commented out but otherwise everything else is enabled and my app is using Turbolinks and running marvellously

**Comment by lucasMesquitaBorges** [comment]
Hello!!
Thanks for your suggestion but we do not plan to perform these features in the laravel-page-speed package!
