### ISSUE TITLE
[Suggestion] - Issue with shouldProcessPageSpeed getting called for each Middleware

### ISSUE THREAD

**Issue by spaceemotion** [renatomarinho/laravel-page-speed#40]
<h2>Detailed description</h2>
<p>The shouldProcessPageSpeed on the base PageSpeed middleware is getting called for each middleware, essentially doing the check for each enabled feature. Now, this would make sense if the config would allow specific middleware to be skipped for some configured route patterns, but it doesn't.</p>
<h2>Context</h2>
<p>Running the pattern check for each middleware sounds expensive the more patterns and page speed features you add to a page request. Reducing the many regex checks will greatly reduce the page load speeds under heavy load.</p>
<p>I can provide a PR if this change is wanted.</p>
<h2>Possible implementation</h2>
<p>This issue proposes introducing a static field that keeps track of whether or not any previous request has passed or not (null = no previous check, true = pass, false = fail).</p>
<h2>Your environment</h2>
<ul>
<li>Homestead on Mac OS Sierra</li>
</ul>

**Comment by joaorobertopb** [comment]
Hi @spaceemotion,
Very well observed!

In the future the idea is to register only a middleware in the Kernel and enable / disable the filters through the configuration file, in this case, it makes sense to have this check in the abstract class.

@renatomarinho , what is your opinion about this?

**Comment by lucasMesquitaBorges** [comment]
This issue was resolved at [2.0.0 version](https://github.com/renatomarinho/laravel-page-speed/tree/2.0.0)!
