### ISSUE TITLE
Console Chrome Error: Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by alejandrozorita** [renatomarinho/laravel-page-speed#43]
HI, I am using your component and it really work!

I only have a question, do you know why Chrome report a error with `\RenatoMarinho\LaravelPageSpeed\Middleware\CollapseWhitespace::class,`?

## Detailed description
I have this code in the middleware:

`
protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \RenatoMarinho\LaravelPageSpeed\Middleware\RemoveComments::class,
        \RenatoMarinho\LaravelPageSpeed\Middleware\CollapseWhitespace::class,
        //\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
    ];
`
And when I check the google console, it throw this error: Uncaught SyntaxError: _Unexpected end of input_

I tryed to delete the middleware 'CollapseWhitespace' and the error disappear.
## Context

It is not very important, but generate a error

## Your environment

* LaravelPageSpeed ^1.8
* Laravel 5.4.*
* PHP: 7.0.24
* Linux Server Centos

**Comment by renatomarinho** [comment]
try it:

protected $middleware = [ \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class, \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class, \App\Http\Middleware\TrimStrings::class, \RenatoMarinho\LaravelPageSpeed\Middleware\RemoveComments::class, \RenatoMarinho\LaravelPageSpeed\Middleware\CollapseWhitespace::class, //\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class, 
**];**

**Comment by mclxly** [comment]
I get the error too.

It's disappeared if I removed all comments in JS.

**Comment by joaorobertopb** [comment]
Hi @alejandrozorita,

Thank you for notifying.

This has already been referenced #30
