### ISSUE TITLE
Disable the laravel page speed service is not working.

### ISSUE THREAD

**Issue by fsuuaas** [renatomarinho/laravel-page-speed#51]
<h2>Detailed description</h2>
<p>I set 'enable' =&gt; env('LARAVEL_PAGE_SPEED_ENABLE', false), to disable laravel page speed service. But its not working. I also set LARAVEL_PAGE_SPEED_ENABLE=false in .env file. But it also not working. How to disable Page Speed Service without commenting Page Speed Middlewares?</p>
<h2>Development environment</h2>
<ul>
<li>Laravel  v5.5</li>
<li>Version used (e.g. PHP 7.1):</li>
<li>Operating system and version (e.g. Windows 10):</li>
</ul>

**Comment by joaorobertopb** [comment]
Hi @fsuuaas,

Has the configuration file been published?

`php artisan vendor:publish --provider="RenatoMarinho\LaravelPageSpeed\ServiceProvider"`

We have some tests that cover this behavior...

https://github.com/renatomarinho/laravel-page-speed/blob/569d50bcd1d1aa59bf076259ddff3e2d7005cd0c/tests/Config/ConfigTest.php#L19

**Comment by fsuuaas** [comment]
Yes I published  configuration file.

**Comment by joaorobertopb** [comment]
Ok man.

I'll try to replicate your setup and run the tests...

**Comment by joaorobertopb** [comment]
I could not replicate the error in my environment.
All the tests are passing and no other user has reported this problem, so i think it's an isolated case.

Thanks
