### ISSUE TITLE
Secure server converting all external links to HTTPS

### ISSUE THREAD

**Issue by BrainBoxLabs** [renatomarinho/laravel-page-speed#53]
We have external partner links stored the database as full URLs (e.g. http://www.bellavistarv.com) that are being displayed on the website. The website is secure (https). With Laravel Page Speed disabled the external links on the website are exactly as they are in the database. When we enabled Laravel Page Speed on our website, those same external links are converted to HTTPS, which return broken URLs.

**Comment by johnhearfield** [comment]
Disable the **TrimURLs** module, since it removes the protocol at the beginning.

**Comment by joaorobertopb** [comment]
Hi @BrainBoxLabs,

I recommend following the suggestion the @johnhearfield.

Do not register: `\RenatoMarinho\LaravelPageSpeed\Middleware\TrimUrls::class

**Comment by BrainBoxLabs** [comment]
Thank you!
