### ISSUE TITLE
js errors after minification

### ISSUE THREAD

**Issue by PhPPgAdminBug** [renatomarinho/laravel-page-speed#55]
<p>Laravel 5.4
Vue.js</p>
<p>Clear installation of LPS package. Now we have errors:</p>
<pre><code>Uncaught SyntaxError: Unexpected end of input
Uncaught SyntaxError: Invalid or unexpected token
Uncaught ReferenceError: PhpDebugBar is not defined
    at search:4
(anonymous) @ search:4
app.js:sourcemap:4572 jQuery.Deferred exception: $ is not a function TypeError: $ is not a function
Uncaught TypeError: $ is not a function</code></pre>
<ul>
<li>PhP 7.1</li>
<li>Windows 10 Pro</li>
<li>Vagrant - Homestead</li>
<li>local project</li>
</ul>

**Comment by poseso** [comment]
any news on this?

**Comment by daniberv** [comment]
Same issue

**Comment by poseso** [comment]
I removed the package, problem solved! 😂

**Comment by muarachmann** [comment]
I had the same issue. It works really fine but noticed my JS functions dont work again. Manually removing them in the `kernel.php` , i found out it was the 	    `\RenatoMarinho\LaravelPageSpeed\Middleware\CollapseWhitespace::class` which had the bug, probably removing spaces it does have to here and there. Aside this the other works fine just that it doesn't minify.

**Comment by joaorobertopb** [comment]
Hi guys,

I'm working on fix.

**Comment by muarachmann** [comment]
Thanks @joaorobertopb it will be a huge update

**Comment by lucasMesquitaBorges** [comment]
This issue was resolved at [2.0.0 version](https://github.com/renatomarinho/laravel-page-speed/tree/2.0.0)!
