### ISSUE TITLE
[pt_BR] - CollapseWhitespace quebrando dropzone.js

### ISSUE THREAD

**Issue by ibrunotome** [renatomarinho/laravel-page-speed#57]
<p>Primeiramente parabéns pelo trabalho Renato, acompanho desde quando o projeto tinha 15 estrelas rsrs. Cheque a compatibilidade do CollapseWhitespace com o plugin dropzone, pois ele não funciona após a aplicação desse middleware, com o erro &quot;Unexpected end of script&quot;.</p>
<p>Mais especificamente, a regra </p>
<p><code>"/\n/" =&gt; '',</code></p>
<p>que está afetando o dropzone.js.</p>
<ul>
<li>Php 7.1.10</li>
<li>Laravel 5.5</li>
<li>local</li>
</ul>

**Comment by renatomarinho** [comment]
@ibrunotome muito obrigado Bruno. 
O package atual existe uma incompatibilidade com javascript diretamente no HTML. Vamos trabalhar para solucionar.

Caso tenha interesse, sinta-se convidado a ajudar com o crescimento do package.

Brazilian storm!

Grande abraço.

**Comment by marcelogarbin** [comment]
Alguma novidade sobre essa questão?

**Comment by lucasMesquitaBorges** [comment]
Essa issue foi corrigida na [versão 2.0.0](https://github.com/renatomarinho/laravel-page-speed/tree/2.0.0)!
