### ISSUE TITLE
A small TrimUrls bug

### ISSUE THREAD

**Issue by vladsad** [renatomarinho/laravel-page-speed#60]
I add google embed map. Here is his code for example 

` <iframe src="https://www.google.ru/maps/embed/....."></iframe>` 

Then if `trim_urls` filter ON, he replace `'/https:/' => ''` and in browsers such as Firefox and Opera (in Chrome works fine )  i catch an error 
>  The Google Maps API server rejected your request. Requests to this API must be over SSL. Load the API with "https://" instead of "http://".

To solve the problem, I think you should just avoid replacing URLs in the <iframe>  :)

**Comment by joaorobertopb** [comment]
Hi @vladsad,
Thanks for the sugestion! But I believe this will not solve the root problem... ( refs #53 )

For now I recommend not register: `\RenatoMarinho\LaravelPageSpeed\Middleware\TrimUrls::class`
