### ISSUE TITLE
trimurls causes Pusher exception

### ISSUE THREAD

**Issue by vesper8** [renatomarinho/laravel-page-speed#61]
When using the TrimUrls middleware (tested on its own with all others disabled)

Connections to Pusher are broken

This error is shown

```
app.js?id=dkjsdflkjsdf:55485 Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":null,"message":"Invalid signature: Expected HMAC SHA256 hex digest of 5601.2191940:presence-chatroom.2:{\"user_id\":205,\"user_
 ...
```

**Comment by joaorobertopb** [comment]
Trimming URLs is considered medium risk. It can cause problems if it uses the wrong base URL. 
References ( #60 #53 ).

Do not register: `\RenatoMarinho\LaravelPageSpeed\Middleware\TrimUrls::class`
