### ISSUE TITLE
TrimUrls is removing necessary information for JSON-LD 

### ISSUE THREAD

**Issue by ahmadalfy** [renatomarinho/laravel-page-speed#66]
This class remove the URL scheme from everywhere.

    \RenatoMarinho\LaravelPageSpeed\Middleware\TrimUrls::class,

This renders the [JSON-LD](https://en.wikipedia.org/wiki/JSON-LD) object invalid and stop Google from properly indexing your rich snippets.
```
<script type="application/ld+json">
{  
   "@context":"http://schema.org",
   "thumbnailUrl":"http://sampleurl"
}
</script>
```
Become this:
```
<script type="application/ld+json">
{  
   "@context":"//schema.org",
   "thumbnailUrl":"//sampleurl"
}
</script>
```
It should automatically exclude these parts

**Comment by joaorobertopb** [comment]
Hi!

Trimming URLs is considered medium risk. It can cause problems if it uses the wrong base URL.
References ( #61 #60 #53 ).

In your case, do not register: \RenatoMarinho\LaravelPageSpeed\Middleware\TrimUrls::class

Soon we will be updating the documentation of the package, leaving more explicit the risks that each filter can cause.
