### ISSUE TITLE
Update to Laravel 5.6

### ISSUE THREAD

**Issue by gbgelado** [renatomarinho/laravel-page-speed#69]
```
- Installation request for renatomarinho/laravel-page-speed ^1.5 -> satisfiable by renatomarinho/laravel-page-speed[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.6.0, 1.7.0, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6].

**Comment by testdnmedia** [comment]
I have used "illuminate/support": "5.3.* || 5.4.* || 5.5.* || 5.6.*", the result remains the same

 Problem 1
    - Conclusion: don't install illuminate/support v5.5.34
    - Conclusion: don't install illuminate/support v5.5.33
    - Conclusion: don't install illuminate/support v5.5.28
    - Conclusion: don't install illuminate/support v5.5.17
    - Conclusion: don't install illuminate/support v5.5.16
    - Conclusion: don't install illuminate/support v5.5.2
    - Conclusion: don't install illuminate/support v5.5.0
    - Conclusion: don't install illuminate/support v5.4.36
    - Conclusion: don't install illuminate/support v5.4.27
    - Conclusion: don't install illuminate/support v5.4.19
    - Conclusion: don't install illuminate/support v5.4.17
    - Conclusion: don't install illuminate/support v5.4.13
    - Conclusion: don't install illuminate/support v5.4.9
    - Conclusion: don't install illuminate/support v5.4.0
    - Conclusion: don't install illuminate/support v5.3.23
    - Conclusion: don't install illuminate/support v5.3.16
    - Conclusion: don't install illuminate/support v5.3.4
    - Installation request for laravel/framework 5.6.* -> satisfiable by laravel/framework[v5.6.0, v5.6.1, v5.6.2, v5.6.3].
    - Installation request for laravel/framework (locked at v5.6.3, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.3].
    - Installation request for codecasts/laravel-jwt ^0.9.0 -> satisfiable by codecasts/laravel-jwt[0.9.0].
    - renatomarinho/laravel-page-speed 1.8.0 requires illuminate/support 5.3.* || 5.4.* || 5.5.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - renatomarinho/laravel-page-speed 1.8.1 requires illuminate/support 5.3.* || 5.4.* || 5.5.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - renatomarinho/laravel-page-speed 1.8.2 requires illuminate/support 5.3.* || 5.4.* || 5.5.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - renatomarinho/laravel-page-speed 1.8.3 requires illuminate/support 5.3.* || 5.4.* || 5.5.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - renatomarinho/laravel-page-speed 1.8.4 requires illuminate/support 5.3.* || 5.4.* || 5.5.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - renatomarinho/laravel-page-speed 1.8.5 requires illuminate/support 5.3.* || 5.4.* || 5.5.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - renatomarinho/laravel-page-speed 1.8.6 requires illuminate/support 5.3.* || 5.4.* || 5.5.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - Conclusion: don't install illuminate/support v5.3.0
    - Installation request for renatomarinho/laravel-page-speed ^1.8 -> satisfiable by renatomarinho/laravel-page-speed[1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6].
