### ISSUE TITLE
Text formatting within textarea

### ISSUE THREAD

**Issue by philmarc** [renatomarinho/laravel-page-speed#73]
When using the `collapse_whitespace` filter, the content of a textarea (indenting) is lost.

This behaviour appears when editing a model that contains a `TEXT` field and that is displayed in a textarea form input on your views.

A quick fix for this is to disable the filter on your "edit" page, by adding a path in your skip routes of the `laravel-page-speed.php` config file:

` 'skip' => [
        '*/edit',
        ...
`

Is there a way to disable whitespace collapsing only for a specific attribute of the DOM, like the textarea input?

**Comment by joaorobertopb** [comment]
Hi!

Not in the moment...

**Comment by kampit** [comment]
Any updates for this one? I got a problem to the `<textarea></textarea>`
