### ISSUE TITLE
Install manually to hosted project.

### ISSUE THREAD

**Issue by jromemcshev** [renatomarinho/laravel-page-speed#74]
Hi, I am new to git and laravel. How can i install this package to my site that is already hosted ? Is this possible ?

**Comment by joaorobertopb** [comment]
Hi!

Install via composer:

```bash
composer require renatomarinho/laravel-page-speed
```

For more details see the readme file.

**Comment by jromemcshev** [comment]
@joaorobertopb  hi i am kinda new. How can i possibly use composer in my site that has been already uploaded ?

**Comment by joaorobertopb** [comment]
Hi!

Here is not the best place for this... I recommend you direct your questions to https://laracasts.com/discuss or https://stackoverflow.com/

Thanks!
