### ISSUE TITLE
Enhancement: Increase internal performance with caching

### ISSUE THREAD

**Issue by Levivb** [renatomarinho/laravel-page-speed#76]
For each added middleware, the `isEnabled` check is executed: https://github.com/renatomarinho/laravel-page-speed/blob/master/src/Middleware/PageSpeed.php#L58

Although the check itself isn't all that much:
```php
$enable = config('laravel-page-speed.enable');
return (is_null($enable))?true: (boolean) $enable;
```

Having `config` called over and over won't do much good to the page speed itself.
It would be nice to store the result of `config('laravel-page-speed.enable')` in a static property of the `abstract` `PageSpeed` class like so:

```php
abstract class PageSpeed
{
        private static $isEnabled;

        protected function isEnable()
        {
            if(!is_null(static::$isEnabled)){
                return static::$isEnabled;
            }
            $enable = config('laravel-page-speed.enable');
            return static::$isEnabled = (is_null($enable))?true: (boolean) $enable;
        }
    ...
}
 ```
*written in github editor, so not PSR-2 compliant ;)*

This way, each `PageSpeed` `Middleware` `class` can leverage from the same `isEnabled` property.

I know it's not a lot of performance gain. But since it's a rather easy addition I reckon it would be a nice small enhancement.

**Comment by joaorobertopb** [comment]
Hi @Levivb !

Could you send PR with these improvements? Be sure to rewrite the tests if necessary.

Thanks for the sugestion!

**Comment by vahidalvandi** [comment]
do in laravel page cache after each refresh compress html or one time compress and next use resent compress page ?
