### ISSUE TITLE
CollapseWhitespace Errors

### ISSUE THREAD

**Issue by Bing1024** [renatomarinho/laravel-page-speed#77]
with BootStrap 4.1
## Error
        $replace = [
            "/\n([\S])/" => '$1',
            "/\r/" => '',
            "/\n/" => '',
            "/\t/" => '',
            "/ +/" => ' ',
            "/> +</" => '><',
        ];

## Suggest

        $replace = [
            "/\n([\S])/" => '$1',
            "/\r/" => '',
            "/\n/" => '',
            "/\t/" => '',
            "/ +/" => ' ',
           "/> +</" => '><', ------ Delete
        ];

**Comment by joaorobertopb** [comment]
Hi @Bing1024,

Can you please give me more details?

**Comment by lucasMesquitaBorges** [comment]
This issue was resolved at [2.0.0 version](https://github.com/renatomarinho/laravel-page-speed/tree/2.0.0)!
