### ISSUE TITLE
Laravel Page Speed doesn't work in Laravel 5.6

### ISSUE THREAD

**Issue by BrayanAngaritaR** [renatomarinho/laravel-page-speed#79]
Hi, I installed the repository in my Laravel project, version **5.6**

It doesn't work, what can I do? Please 
If someone had this problem, please let me know. Thanks!

**Comment by AskAlice** [comment]
Did you run `php artisan vendor:publish --provider="RenatoMarinho\LaravelPageSpeed\ServiceProvider"` and add the middleware like it says in the somewhat ambiguous installation instructions? It's easy to interpret that installing it is all you need to do, but you do need to publish the vendor configs and add the middleware for it to do anything

**Comment by kostaspapad** [comment]
I have the same problem too
