### ISSUE TITLE
Remove comment doesn't remove js and css comment

### ISSUE THREAD

**Issue by dels07** [renatomarinho/laravel-page-speed#82]
## Detailed description

**RemoveComments** middleware only remove HTML comment and not removing comments from inline css/js especially single line comment (**//**), so it will not work correctly with **CollapseWhitespace**, 

## Context

This will break some javascript and css that have comment single line comment.

## Possible implementation

Remove both multiline and single line comment on both inline js and css
_References:_
- https://stackoverflow.com/questions/5989315/regex-for-match-replacing-javascript-comments-both-multiline-and-inline
- https://blog.ostermiller.org/find-comment

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* PHP 7.2
* Windows 10 Pro
* Laravel 5.6.34

**Comment by marcelogarbin** [comment]
any news?

**Comment by lucasMesquitaBorges** [comment]
This issue was resolved at [2.0.0 version](https://github.com/renatomarinho/laravel-page-speed/tree/2.0.0)!
