### ISSUE TITLE
install issue in laravel 5.7

### ISSUE THREAD

**Issue by aboda1986** [renatomarinho/laravel-page-speed#83]
## Detailed description

when i try to install laravel-page-speed using composer, i ll see the following message:

Installation failed, reverting ./composer.json to its original content.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* PHP 7.2:
* window 10

**Comment by aboda1986** [comment]
Any Update?

**Comment by dels07** [comment]
Composer still not reading the release/tag 1.8.8
https://packagist.org/packages/renatomarinho/laravel-page-speed

Installing using dev-master also not working

**Comment by aboda1986** [comment]
until now the installer not working on laravel 5.7
