### ISSUE TITLE
[BUG] laravel-page-speed CHANGES (!) URLs, results in broken links

### ISSUE THREAD

**Issue by panique** [renatomarinho/laravel-page-speed#85]
## Detailed description

Hi, I had a major issue with thousands of broken affiliate links in a project and could track down the issue to laravel-page-speed actually CHANGING the links. It's a major bug and reproduceable. IMPORTANT: Most browsers have an quite good internal auto-correction of URLs, so it was hard to find the real problem. The bug is not "visible" in most browsers except Safari on macOS (Sierra, High Sierra, (maybe) Mojave) and Safari on iPhones in generations SE, 6, 7, X and probably iOS 11 and 12.

## Context

The example link is a tracking / affiliate link into a german fashion shop. I'm posting this just for clear demo purposes, not for any shady linkbuilding purposes or affiliate tricks. I'm do not work for the affiliate company or the shop itself, i'm just using tracking / affiliate links in my own project for commercial purposes. I'll not get any money from anybody for you clicking on the link (it's %-per-sale affiliate). Just to make this clear...

I'm posting untouched URLs directly from database inside Laravel blade templates. Raw link (note that this is actually a tracking link that has a second URL as parameter (`diurl=https://www.mira...`)):

```
https://partners.webmasterplan.com/click.asp?ref=839072&site=7270&type=text&tnb=74&diurl=https://www.mirapodo.de/converse-essentials-winterwool-jogginghose-herren-anthrazit-8519541.html
```

I'm showing the untouched link in the view like:

```php
<a href="{{ $url }}">Link title</a>
```

which then renders to CHANGED links like:

```
https://partners.webmasterplan.com/click.asp?ref=839072&site=7270&type=text&tnb=74&diurl=//www.mirapodo.de/converse-essentials-winterwool-jogginghose-herren-anthrazit-8519541.html
```

The link is different, note that the second *https* has been removed: `diurl=//www.mira`!!!

This is autocorrected by most browsers except Safari. This subtle change might have massive effects in entire projects being broken for the entire Mac / iPhone world.

## Possible implementation

I highly adore your project and am working on a fix.

## Quick fix

Turn off the entire usage of the class inside app/http/Kernel.php (not app/Console/Kernel.php), and do a `php artisan config:clear` and `php artisan cache:clear` afterwards.

```
\RenatoMarinho\LaravelPageSpeed\Middleware\TrimUrls::class,
```

## Your environment

* using laravel-page-speed v1.8.7
* inside a Laravel 5.6 application, PHP 7.2.9, nginx
* Live-example on https://www.chicchic.de/filter?q=converse+50 - try to click on the first link (a grey jogging pant for 49.92€) in Firefox and Safari, you'll see Firefox working, Safari breaking.

By the way, thanks for such a great tool, except from that bug it's awesome! <3

**Comment by joaorobertopb** [comment]
Hi @panique,
Thanks for notification, but this is not necessarily a bug ...

This package is inspired by (https://www.modpagespeed.com/) as well as Mod Page Speed, all middlewares have an error level for the application.

_\RenatoMarinho\LaravelPageSpeed\Middleware\TrimUrls::class_ **is considered medium risk**. It can cause problems if it uses the wrong base URL. This can happen, for example, if you serve HTML that will be pasted verbatim into other HTML pages. If URLs are trimmed on the first page, they will be incorrect for the page they are inserted into. In this case, **just disable the middleware**.


Let's work on building a Wiki to make this clearer for all users. ( Help Wanted )

**Comment by jcfariadias** [comment]
I had this problem too where links were stripped from the protocol (https://www ...  would turn //www...). This is "dangerous" for sites that rely heavily on SEO techniques and should be stated that. It breaks almost every google test on the page like, canonicals and structured data, all get malformed url errors. 

If this really is a "feature" please have this in mind and alert the users

**Comment by joaorobertopb** [comment]
Yes,

Added warning to users in the README file.
