### ISSUE TITLE
1.8.8 cannot install from composer

### ISSUE THREAD

**Issue by forddyce** [renatomarinho/laravel-page-speed#87]
Cannot find version 1.8.8 from composer. By default running `composer require` will install 1.8.7 version.

![screenshot from 2018-09-12 15-43-23](https://user-images.githubusercontent.com/6212875/45413123-9a086a00-b6a2-11e8-862e-1aa93546db3c.png)

**Comment by joaorobertopb** [comment]
I do not have access to the Packagist of this repository...

@renatomarinho, can you help us, please?

**Comment by renatomarinho** [comment]
Hey @forddyce , 

Correct is : composer require renatomarinho/laravel-page-speed

**Comment by renatomarinho** [comment]
Here is fine.

Using version ^1.8 for renatomarinho/laravel-page-speed
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update

composer.json
{
    "require": {
        "renatomarinho/laravel-page-speed": "^1.8"
    }
}

**Comment by forddyce** [comment]
> Here is fine.
> 
> Using version ^1.8 for renatomarinho/laravel-page-speed
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Nothing to install or update
> 
> composer.json
> {
> "require": {
> "renatomarinho/laravel-page-speed": "^1.8"
> }
> }

Ok I see you have updated the packagist. Thank you.

**Comment by renatomarinho** [comment]
Here is fine.

Using version ^1.8 for renatomarinho/laravel-page-speed
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update

composer.json
{
"require": {
"renatomarinho/laravel-page-speed": "^1.8"
}
}

**Comment by renatomarinho** [comment]
@forddyce ... yes!

**Comment by joaorobertopb** [comment]
Thanks @renatomarinho!

All right now.
