### ISSUE TITLE
Auto Discovery NOT Working

### ISSUE THREAD

**Issue by TahseenAlaa** [renatomarinho/laravel-page-speed#88]
Auto Discovery NOT Working on fresh Laravel 5.5.*

## Detailed description

First I want to thanks you for making this Amazing package in open source community, Actually After installing this package on fresh laravel 5.5.* It is not working so I forced to add the middleware and Serviceproviders my self,  after that It working fine.

**Comment by joaorobertopb** [comment]
:+1:
