### ISSUE TITLE
Call to a member function exception object 

### ISSUE THREAD

**Issue by testdnmedia** [renatomarinho/laravel-page-speed#89]
the bug does not appear in view only in the storage / logs folder and every time the load view error is the same

[2018-10-03 02:56:35] local.ERROR: Call to a member function getContent() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getContent() on null at /home/dev/webapps/myapp/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php:33)
[laravel-2018-10-03.log](https://github.com/renatomarinho/laravel-page-speed/files/2440401/laravel-2018-10-03.log)

composer.json
    "require": {
        "php": "^7.1.0",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0",
        "kreait/firebase-php": "dev-master",
        "spatie/laravel-varnish": "dev-master",
        "spatie/laravel-analytics": "dev-master",
        "hisorange/browser-detect": "^3.1.4",
        "torann/geoip": "dev-master",
        "balping/laravel-blade-function": "dev-master",
        "intervention/image": "dev-master",
        "laravelcollective/html": "dev-master",
        "gufy/cpanel-whm": "dev-master",
        "publiux/laravelcdn": "dev-master",
        "silber/page-cache": "dev-master"
    },
    "require-dev": {
        "filp/whoops": "^2.0",
        "mockery/mockery": "^1.0",
        "phpunit/phpunit": "^6.0 ||^7.0",
        "symfony/thanks": "^1.0",
        "phpspec/phpspec": "^4.3",
        "gentor/mautic-api-laravel":"dev-master",
        "arcanedev/log-viewer": "^4.5.2",
        "beyondcode/laravel-dump-server": "^1.0",
        "fzaninotto/faker": "^1.4",
        "nunomaduro/collision": "^2.0",
        "renatomarinho/laravel-page-speed": "dev-master",
        "predis/predis": "dev-master",
        "components/angular.js": "dev-master",
        "illuminate/html": "dev-master",
        "laravel-doctrine/acl": "dev-master",
        "laravel/tinker": "dev-master",
        "twbs/bootstrap": "dev-master",
        "firebase/php-jwt": "^5.0",
        "lcobucci/jwt": "3.3.x-dev",
        "symfony/symfony": "^4.1"
    },

**Comment by joaorobertopb** [comment]
Is that solved?
you were the only user who reported this problem.

Sounds like an isolated case to me.
