### ISSUE TITLE
Slick slider stops working after plugin installation

### ISSUE THREAD

**Issue by bhavikji** [renatomarinho/laravel-page-speed#95]
Hello, I have installed this plugin in my project and as I installed the plugin the slick slider stops working it appears that plugins stop its initialization. Any help in this?

I am working on PHP 7.2, Ubuntu 18.04 and on Laravel 5.6

To reproduce this issue, you can create a fresh Laravel app and create a basic demo of the slick slider and then install the plugin.

**Comment by joaorobertopb** [comment]
Hi @bhavikji

Can you please show me more details?
how your middlewares were registered in the `app\Http\Kernel.php` file?

**Comment by joaorobertopb** [comment]
probably this problem is being caused by the bug reported in #30 .
