### ISSUE TITLE
Always exclude StreamedResponse

### ISSUE THREAD

**Issue by TivoSoho** [renatomarinho/laravel-page-speed#97]
## Detailed description

Bug: currently it tries to handle streamed response. While there is the option to exclude pages, those are more for pages where the context cannot handle being processed and you do not know that it can't. StreamedResponse however does not work due to the code itself and throws an exception: **content cannot be set on a StreamedResponse instance**. To me it is the same as BinaryFileResponse - we know this can't be handled.

## Context

Saves us the trouble of excluding every path that would respond in a streamed response.

## Possible implementation

Like you check if response is instance of BinaryFileResponse, you should check if it is part of StreamedResponse and not handle such requests.

## Your environment

Laravel: 5.7.8
OS: Ubuntu (Homestead)

**Comment by BrandonDR** [comment]
^ bump

**Comment by joaorobertopb** [comment]
Hi @TivoSoho

Thanks for notification. i'll check it out.

**Comment by percymamedy** [comment]
Hi @joaorobertopb 

I have created the following PR for this #101 as I faced a similar situation.

Thanks.

**Comment by percymamedy** [comment]
You are welcome @joaorobertopb ! 

Always happy to help and contribute !!. :smiley: :smiley:
