### ISSUE TITLE
Laravel Page Speed makes erros in my structures data

### ISSUE THREAD

**Issue by sera527** [renatomarinho/laravel-page-speed#98]
Hello!
I posted structured data on my website right in the template in ld + json format. My template:
![2018-12-16 17-48-01](https://user-images.githubusercontent.com/9019284/50055712-19eb1800-015b-11e9-99a4-e245ff602e33.png)
Google Structured Data Testing Tool:
![2018-12-16 17-28-11](https://user-images.githubusercontent.com/9019284/50055722-4ef76a80-015b-11e9-9cd6-8d9e40fdce6a.png)

* PHP 7.2, Laravel 5.5
* https://barrockco.org.ua/

**Comment by joaorobertopb** [comment]
Hi!

Do not register the **\RenatoMarinho\LaravelPageSpeed\Middleware\TrimUrls::class** in the **Kernel.php** file.


**\RenatoMarinho\LaravelPageSpeed\Middleware\TrimUrls::class** is considered **medium risk**. It can cause problems if it uses the wrong base URL. This can happen, for example, if you serve HTML that will be pasted verbatim into other HTML pages. If URLs are trimmed on the first page, they will be incorrect for the page they are inserted into. In this case, just disable the middleware.
